#!/bin/sh

pacman_install() {
    pacman -S "$@" --needed --noconfirm
}

pacman_remove() {
    pacman -Runs "$@" --noconfirm
}

create_link() {
    local source_file=$1;
    local target_file=$2;
    if [ -e "$target_file" ]; then
        rm -r "$target_file"
    fi
    ln -s "$source_file" "$target_file"
}
