#!/bin/sh /etc/rc.common
#
# this script used in /etc/init.d

START=19
NAME=crystal
CUR_DIR=$(dirname "$(readlink -f /etc/init.d/$NAME)")

start() {
    $CUR_DIR/ctrl start
}

stop() {
    $CUR_DIR/ctrl stop
}

restart() {
    $CUR_DIR/ctrl restart
}
