#!/bin/sh

set -e

CUR_DIR="$(dirname -- "${BASH_SOURCE[0]}")"

ACTION=$1
PKG_NAME=$2

# transform PKG_NAME to array
if [ -z "$PKG_NAME" ]; then
    PKG_NAME=($(ls $CUR_DIR/packages))
else
    PKG_NAME=($PKG_NAME)
fi

if [ "$ACTION" = "setup" ]; then
    opkg update
fi

for pkg in "${PKG_NAME[@]}"; do
    sh $CUR_DIR/packages/$pkg/ctrl $ACTION
done
