#!/bin/sh

set -e

# go to current dir
cd "$(dirname -- "${BASH_SOURCE[0]}")"

ACTION=$1
PKG_NAME=$2

# transform PKG_NAME to array
if [ -z "$PKG_NAME" ]; then
    PKG_NAME=($(ls ./packages))
else
    PKG_NAME=($PKG_NAME)
fi

for pkg in "${PKG_NAME[@]}"; do
    sh ./packages/$pkg/ctrl $ACTION
done
