server {
    listen __listen__ ssl http2 default_server;
    ssl_reject_handshake on;
}

server {
    listen __listen__ ssl http2;
    server_name __domain__;

    ssl_certificate /etc/letsencrypt/live/__domain__/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/__domain__/privkey.pem;
    ssl_protocols TLSv1.3;
    ssl_ecdh_curve X25519:prime256v1;

    root __site_dir__;

    location = / {
        add_header WWW-Authenticate 'Basic realm="Restricted"' always;
        return 401;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
